config_version = 13

[accessibility]
ui_scale = 0.95000000670552254

[bar.default]
capsule = true
capsule_foreground = "primary"
capsule_radius = 10
center = [ "group:g4" ]
end = [ "tray", "group:g1", "group:g2", "group:g3" ]
margin_ends = 0
radius_bottom_left = 7
radius_bottom_right = 7
radius_top_left = 0
radius_top_right = 0
scale = 0.95000000670552254
start = [ "date", "active_window" ]
thickness = 27

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    foreground = "primary"
    id = "g1"
    members = [ "clipboard", "notifications", "network" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    foreground = "primary"
    id = "g2"
    members = [ "volume", "brightness", "battery" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    foreground = "primary"
    id = "g3"
    members = [ "control-center", "session" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    foreground = "primary"
    id = "g4"
    members = [ "clock", "workspaces" ]
    opacity = 1.0
    padding = 6.0

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 683.0
    cy = 586.0
    output = "eDP-1"
    placement_height = 768.0
    placement_width = 1366.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[shell]
button_borders = false
input_borders = false
popup_borders = false

    [shell.animation]
    enabled = false

[theme]
builtin = "Dracula"
pure_black_dark = true

[wallpaper.default]
path = "/usr/share/noctalia/assets/noctalia-wallpaper.png"

[wallpaper.last]
path = "/usr/share/noctalia/assets/noctalia-wallpaper.png"

[widget.active_window]
icon_size = 13
min_length = 0

[widget.battery]
show_label = false

[widget.brightness]
show_label = false

[widget.network]
show_label = false

[widget.volume]
show_label = false

[widget.workspaces]
active_pill_size = 4.0
empty_color = "surface"
inactive_pill_size = 1.2000000000000002
pill_scale = 0.65000000000000002
scale = 0.94999999999999996
show_labels = false