color0 #110118
color1 #e80e4f
color2 #cb62f8
color3 #e8a70e
color4 #bc39f3
color5 #e80ebc
color6 #a70ee8
color7 #e8bcfb
color8 #310345
color9 #c73859
color10 #da8efa
color11 #f3bc39
color12 #ca65f6
color13 #f339ce
color14 #bc39f3
color15 #f7e7fe

cursor                #f7e7fe
cursor_text_color     #110118
background            #110118
foreground            #f7e7fe
selection_foreground  #f7e7fe
selection_background  #280338
active_border_color   #772e96
inactive_border_color #280338
url_color             #772e96

active_tab_foreground   #110118
active_tab_background   #772e96
inactive_tab_foreground #e8bcfb
inactive_tab_background #280338
cursor_trail_color      #e8bcfb
